export { default as Instagram } from './Instagram'
export { default as ArrowRight } from './ArrowRight'
export { default as Person } from './Person'
export { default as Search } from './Search'
export { default as LogoWhite } from './LogoWhite'
export { default as ChevronRight } from './ChevronRight'
export { default as ImageIcon } from './Image'
